### ISSUE TITLE
Linux release builds linked against too recent version of libc

### ISSUE THREAD

**Issue by oleg-vinted** [vinted/kafka-elasticsearch-tool#10]
KET doesn't run on Ubuntu 20.04 which ships glibc 2.31 ([source](https://packages.ubuntu.com/focal/libc-bin)).

```
./ket: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./ket)
```

I'm not familiar with Clojure, but I think we should either link against an older version of glibc or link it statically.

@dainiusjocas

**Comment by dainiusjocas** [comment]
I think linking statically is an easy option to try.
